spring.application.name=16_taovankhanh_22714961
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_exam_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG
logging.level.com.example.__taovankhanh_22711831=DEBUG
